import {

  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'
import type {NavigationTree} from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
  {
    key: 'home',
    path: '/home',
    title: 'Home',
    translateKey: 'nav.home',
    icon: 'home',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: 'files',
    path: '/files',
    title: 'Files',
    translateKey: 'nav.files',
    icon: 'filebrowser',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },


  {
    key: 'logs',
    path: '',
    title: 'Logs',
    translateKey: 'na.logs',
    icon: '',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [],
  },
  {
    key: 'all.all',
    path: '',
    title: 'All',
    translateKey: '',
    icon: 'all',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'All.Front',
        path: '/allFront',
        title: 'Front',
        isExternalLink: false,
        translateKey: 'nav.Front.tsx',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'All.Back',
        path: '/allBack',
        title: 'Back',
        isExternalLink: false,
        translateKey: 'nav.Back.tsx',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'All.all',
        path: '/allAll',
        title: 'All',
        isExternalLink: false,
        translateKey: 'nav.All.tsx',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'fun-client',
    path: '',
    title: 'Fun-Client',
    isExternalLink: false,
    translateKey: 'nav.Func-client',
    icon: 'client',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'fun-client.front',
        path: '/Front',
        title: 'Front',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'fun-client.back',
        path: '/Back',
        title: 'Back',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'fun-client.all',
        path: '/All',
        title: 'All',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'fun-frontend',
    path: '',
    title: 'Fun-Frontend',
    isExternalLink: false,
    translateKey: 'nav.Fun-frontend',
    icon: 'frontend',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'fun-frontend.front',
        path: '/Front',
        title: 'Front',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'fun-frontend.back',
        path: '/Back',
        title: 'Back',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'fun-frontend.all',
        path: '/All',
        title: 'All',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'hb-client',
    path: '',
    title: 'Hb-Client',
    isExternalLink: false,
    translateKey: 'nav.HB-client',
    icon: 'hbClient',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu:  [
      {
        key: 'hb-client.front',
        path: '/Front',
        title: 'Front',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'hb-client.back',
        path: '/Back',
        title: 'Back',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'hb-client.all',
        path: '/All',
        title: 'All',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'hb-gateway',
    path: '',
    title: 'HB-Gateway',
    isExternalLink: false,
    translateKey: 'nav.Hb-gateway',
    icon: 'gateway',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'hb-gateway.front',
        path: '/Front',
        title: 'Front',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'hb-gateway.back',
        path: '/Back',
        title: 'Back',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'hb-gateway.all',
        path: '/All',
        title: 'All',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'file-browser',
    path: '',
    title: 'File-Browser',
    isExternalLink: false,
    translateKey: 'nav.File-browser',
    icon: 'filebrowser',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'file-browser.front',
        path: '/Front',
        title: 'Front',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'file-browser.back',
        path: '/Back',
        title: 'Back',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'file-browser.all',
        path: '/All',
        title: 'All',
        isExternalLink: false,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },

  {
    key: 'funttastic',
    path: '',
    title: 'Funttastic',
    translateKey: 'nav.collapseMenu.collapseMenu',
    icon: 'fun',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'funttasticDiscord',
        path: 'https://discord.com/invite/zNzpPhHF86',
        title: 'Discord',
        isExternalLink: true,
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'funttasticTelegram',
        path: 'https://t.me/FunttasticLabs',
        isExternalLink: true,
        title: 'Telegram',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'funttasticGithub',
        path: 'https://github.com/funttastic/',
        isExternalLink: true,
        title: 'Github',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'funttasticWebsite',
        path: 'https://www.funttastic.com/',
        isExternalLink: true,
        title: 'Website',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'funttasticInstagram',
        path: 'https://www.instagram.com/funttastic/',
        isExternalLink: true,
        title: 'Instagram',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'funttasticMail',
        path: 'mailto:contact@funttastic.com',
        title: 'E-Mail',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'kujira',
    path: '',
    title: 'Kujira',
    translateKey: '',
    icon: 'kujira',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'kujiraWebsite',
        path: 'https://kujira.network/',
        isExternalLink: true,
        title: 'Website',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'kujiraDapps',
        path: 'https://kujira.network/dapps',
        isExternalLink: true,
        title: 'Kujira dApps',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'kujiraFIN',
        path: 'https://fin.kujira.network/',
        isExternalLink: true,
        title: 'Kujira FIN',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'kujiraBLUE',
        path: 'https://blue.kujira.network/',
        isExternalLink: true,
        title: 'Kujira BLUE',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'kujiraFinder',
        path: 'https://finder.kujira.network/kaiyo-1',
        isExternalLink: true,
        title: 'Kujira Finder',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'kujiraEcosystem',
        path: 'https://kujira.network/ecosystem',
        isExternalLink: true,
        title: 'Kujira Ecosystem',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'kujiraDocumentation',
        path: 'https://docs.kujira.app/introduction/readme',
        isExternalLink: true,
        title: 'Documentation',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'hummingbot',
    path: '',
    title: 'Hummingbot',
    translateKey: '',
    icon: 'hummingbot',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: 'hummingbotWebsite',
        path: 'https://hummingbot.org/',
        isExternalLink: true,
        title: 'Website',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'hummingbotGuide',
        path: 'https://hummingbot.org/installation/',
        isExternalLink: true,
        title: 'Hummingbot Installation Guide',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
]

export default navigationConfig
